"""
Integrantes do grupo 10:

Gustavo Meirelles Festa
Paulo Henrique Pires Cordeiro
Paula Silveira e Silva
"""

import requests

nomes_moedas = {
    "BRL": "reais",
    "AED": "dirhams dos Emirados Árabes Unidos",
    "AFN": "afeganes",
    "ALL": "leks",
    "AMD": "drams armênios",
    "ANG": "florins das Antilhas Holandesas",
    "AOA": "kwanzas",
    "ARS": "pesos argentinos",
    "AUD": "dólares australianos",
    "AWG": "florins arubanos",
    "AZN": "manats azeris",
    "BAM": "marcos conversíveis bósnios",
    "BBD": "dólares de Barbados",
    "BDT": "takas de Bangladesh",
    "BGN": "levs búlgaros",
    "BHD": "dinares do Bahrein",
    "BIF": "francos burundianos",
    "BMD": "dólares das Bermudas",
    "BND": "dólares de Brunei",
    "BOB": "bolivianos",
    "BSD": "dólares das Bahamas",
    "BTN": "ngultrums do Butão",
    "BWP": "pulas de Botsuana",
    "BYN": "rublos bielorrussos",
    "BZD": "dólares de Belize",
    "CAD": "dólares canadenses",
    "CDF": "francos congolês",
    "CHF": "francos suíços",
    "CLP": "pesos chilenos",
    "CNY": "yuans chineses",
    "COP": "pesos colombianos",
    "CRC": "colóns da Costa Rica",
    "CUP": "pesos cubanos",
    "CVE": "escudos cabo-verdianos",
    "CZK": "coroas checas",
    "DJF": "francos do Djibuti",
    "DKK": "coroas dinamarquesas",
    "DOP": "pesos dominicanos",
    "DZD": "dinares argelinos",
    "EGP": "libras egípcias",
    "ERN": "nakfas da Eritreia",
    "ETB": "birrs etíopes",
    "EUR": "euros",
    "FJD": "dólares fijianos",
    "FKP": "libras das Malvinas",
    "FOK": "coroas feroesas",
    "GBP": "libras esterlinas",
    "GEL": "laris georgianos",
    "GGP": "libras de Guernsey",
    "GHS": "cedis ganeses",
    "GIP": "libras de Gibraltar",
    "GMD": "dalasis gambianos",
    "GNF": "francos guineanos",
    "GTQ": "quetzais guatemaltecos",
    "GYD": "dólares guianenses",
    "HKD": "dólares de Hong Kong",
    "HNL": "lempiras hondurenhas",
    "HRK": "coroas croatas",
    "HTG": "gourdes haitianos",
    "HUF": "forints húngaros",
    "IDR": "rupias indonésias",
    "ILS": "shekels israelenses",
    "IMP": "libras da Ilha de Man",
    "INR": "rupias indianas",
    "IQD": "dinares iraquianos",
    "IRR": "riais iranianos",
    "ISK": "coroas islandesas",
    "JEP": "libras de Jersey",
    "JMD": "dólares jamaicanos",
    "JOD": "dinares jordanianos",
    "JPY": "ienes japoneses",
    "KES": "xelins quenianos",
    "KGS": "soms quirguizes",
    "KHR": "riéis cambojanos",
    "KID": "dólares kiribatianos",
    "KMF": "francos comorianos",
    "KRW": "wons sul-coreanos",
    "KWD": "dinares kuwaitianos",
    "KYD": "dólares das Ilhas Cayman",
    "KZT": "tenges cazaques",
    "LAK": "kips laosianos",
    "LBP": "libras libanesas",
    "LKR": "rupias do Sri Lanka",
    "LRD": "dólares liberianos",
    "LSL": "lotis lesotianos",
    "LYD": "dinares líbios",
    "MAD": "dirhams marroquinos",
    "MDL": "leus moldávios",
    "MGA": "ariarys malgaxes",
    "MKD": "dinares macedônios",
    "MMK": "kyats birmaneses",
    "MNT": "tugriks mongóis",
    "MOP": "patacas de Macau",
    "MRU": "ouguiyas mauritanianos",
    "MUR": "rupias mauricianas",
    "MVR": "rufiyaas maldivos",
    "MWK": "kwachas malauianos",
    "MXN": "pesos mexicanos",
    "MYR": "ringgits malaios",
    "MZN": "meticais moçambicanos",
    "NAD": "dólares namibianos",
    "NGN": "nairas nigerianas",
    "NIO": "córdobas nicaraguenses",
    "NOK": "coroas norueguesas",
    "NPR": "rupias nepalesas",
    "NZD": "dólares neozelandeses",
    "OMR": "riais omanenses",
    "PAB": "balboas panamenhos",
    "PEN": "novos soles peruanos",
    "PGK": "kinas papuásios",
    "PHP": "pesos filipinos",
    "PKR": "rupias paquistanesas",
    "PLN": "zlotys poloneses",
    "PYG": "guaranis paraguaios",
    "QAR": "riais catarianos",
    "RON": "leus romenos",
    "RSD": "dinares sérvios",
    "RUB": "rublos russos",
    "RWF": "francos ruandeses",
    "SAR": "riais sauditas",
    "SBD": "dólares das Ilhas Salomão",
    "SCR": "rupias seichelenses",
    "SDG": "libras sudanesas",
    "SEK": "coroas suecas",
    "SGD": "dólares de Singapura",
    "SHP": "libras de Santa Helena",
    "SLL": "leões da Serra Leoa",
    "SOS": "xelins somalis",
    "SRD": "dólares surinameses",
    "SSP": "libras sul-sudanesas",
    "STN": "dobras de São Tomé e Príncipe",
    "SYP": "libras sírias",
    "SZL": "lilangeni suazis",
    "THB": "bahts tailandeses",
    "TJS": "somonis tajiques",
    "TMT": "manats turcomenos",
    "TND": "dinares tunisianos",
    "TOP": "paʻangas tonganeses",
    "TRY": "liras turcas",
    "TTD": "dólares de Trinidad e Tobago",
    "TVD": "dólares tuvalenses",
    "TWD": "novos dólares taiwaneses",
    "TZS": "xelins tanzanianos",
    "UAH": "hryvnias ucranianas",
    "UGX": "xelins ugandenses",
    "USD": "dólares americanos",
    "UYU": "pesos uruguaios",
    "UZS": "soms uzbeques",
    "VES": "bolívares venezuelanos",
    "VND": "dongs vietnamitas",
    "VUV": "vatus vanuatuanos",
    "WST": "talas samoanos",
    "XAF": "francos CFA da África Central",
    "XCD": "dólares do Caribe Oriental",
    "XDR": "direitos especiais de saque (FMI)",
    "XOF": "francos CFA da África Ocidental",
    "XPF": "francos CFP",
    "YER": "riais iemenitas",
    "ZAR": "rands sul-africanos",
    "ZMW": "kwachas zambianos",
    "ZWL": "dólares zimbabuanos"
}

url = 'https://api.exchangerate-api.com/v4/latest/BRL'
moeda = input('Digite a sigla da moeda para conversão: ').upper()

response = requests.get(url)
data = response.json()

if moeda in data['rates']:
    nome = nomes_moedas.get(moeda)
    print(f"O Real vale {data['rates'][moeda]:.2f} {nome}.")
else:
    print('Moeda não encontrada!')