swagger: "2.0"
info:
  title: API de Usuários
  description: API simples de CRUD para usuários
  version: "1.0.0"

paths:
  /users:
    get:
      summary: Lista todos os usuários
      responses:
        200:
          description: Lista de usuários retornada com sucesso
          schema:
            type: object
            properties:
              mensagem:
                type: string
              dados:
                type: array
                items:
                  $ref: "#/definitions/User"

    post:
      summary: Cria um novo usuário
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: Usuário criado com sucesso

  /users/{id}:
    get:
      summary: Retorna um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Usuário encontrado
        404:
          description: Usuário não encontrado
    put:
      summary: Atualiza usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              nome:
                type: string
              email:
                type: string
      responses:
        200:
          description: Usuário atualizado
        404:
          description: Usuário não encontrado
    delete:
      summary: Deleta um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Usuário excluído
        404:
          description: Usuário não encontrado
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      nome:
        type: string
      email:
        type: string